tarefa 12

diff --git a/.github/workflows/deploy-k8s.yml b/.github/workflows/deploy-k8s.yml
--- a/.github/workflows/deploy-k8s.yml
+++ b/.github/workflows/deploy-k8s.yml
@@ -22,18 +22,47 @@ jobs:
           java-version: '17'
           distribution: 'adopt'
 
-      - name: Dar permissão de execução ao mvnw
+      - name: Give execution permission to mvnw
         run: chmod +x status-service/mvnw
 
       - name: Build with Maven
         run: |
-          cd status-service # Navegar até o diretório do serviço
-          ./mvnw clean verify # ou 'mvn clean verify' se não usar o wrapper
+          cd status-service # Navigate to the service directory
+          ./mvnw clean verify # or 'mvn clean verify' if not using the wrapper
 
       - name: Build Docker image
         run: |
           docker build -t status-service:latest ./status-service
-  
-      - name: Deploy to Kubernetes
+
+      - name: Install KinD
+        run: |
+          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.16.0/kind-linux-amd64
+          chmod +x ./kind
+          sudo mv ./kind /usr/local/bin/
+
+      - name: Create KinD cluster
+        run: kind create cluster
+
+      - name: Load Docker image into KinD
+        run: |
+          kind load docker-image status-service:latest
+
+      - name: Deploy to KinD Kubernetes
         run: |
           kubectl apply -f k8s/status.yml
+
+          - name: Run Tests
+          run: |
+            # Aguarde um pouco para garantir que o serviço esteja ativo
+            sleep 10 
+  
+            # Teste a URL do serviço
+            response=$(curl --write-out "%{http_code}" --silent --output /dev/null http://localhost:8081/status)
+  
+            # Verifique o código de status HTTP
+            if [ "$response" -eq 200 ]; then
+              echo "Test passed: Service is active!"
+            else
+              echo "Test failed: Service returned status code $response"
+              exit 1
+            fi
